#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   https://www.kitteh.org
#
#  See documentation for details:
#  https://dev.bukkit.org/projects/vanish/pages/configuration
#
fakeannounce:
    # This only controls delayed fake join messages for players who joined silently.
    # It does not make players join vanished.
    automaticforsilentjoin: true

join:
    vanish-on-join: false

hooks:
    essentials: true
    discordsrv: false
    squaremap: false
    luckperms: true

permissionsupdates:
    checkonworldchange: false

effects:
    lightning:
        count: 30

permtest: false
debug: false
double-sneak-during-vanish-switches-gamemode:
    enabled: false
    max-ms-time-between-sneaks: 500
    message: '&aGameMode changed!'

configVersionDoNotTouch:
    SeriouslyThisWillEraseYourConfig: 11
